export function getCssContent(): string {
    return [
        ':root{--bg:#0d1117;--surface:#161b22;--surface2:#1c2333;--border:#30363d;--text:#e6edf3;--text2:#8b949e;--accent:#58a6ff;--accent2:#bc8cff;--green:#3fb950;--red:#f85149;--orange:#d29922;--cyan:#39d2c0;--gradient:linear-gradient(135deg,#58a6ff 0%,#bc8cff 100%)}',
        '*{margin:0;padding:0;box-sizing:border-box}',
        "body{background:var(--bg);color:var(--text);font-family:'Segoe UI',system-ui,sans-serif;overflow:hidden;height:100vh}",
        '#app{display:flex;flex-direction:column;height:100vh}',
        '#topbar{display:flex;align-items:center;justify-content:space-between;padding:10px 20px;background:var(--surface);border-bottom:1px solid var(--border)}',
        '.logo{font-size:16px;font-weight:700;background:var(--gradient);-webkit-background-clip:text;-webkit-text-fill-color:transparent}',
        '.status{font-size:12px;color:var(--text2);padding:4px 12px;border-radius:12px;background:var(--surface2)}',
        '#toolbar{display:flex;flex-direction:column;background:var(--surface);border-bottom:1px solid var(--border)}',
        '#tabs{display:flex;gap:4px;padding:8px 20px 0}',
        '.tab{background:none;border:none;color:var(--text2);padding:8px 16px;cursor:pointer;border-radius:8px 8px 0 0;font-size:13px;transition:all .2s}',
        '.tab:hover{color:var(--text);background:var(--surface2)}',
        '.tab.active{color:var(--accent);background:var(--surface2);font-weight:600}',
        '#actions{display:flex;gap:8px;padding:10px 20px;border-bottom:1px solid var(--border);background:var(--bg)}',
        '.action-btn{background:var(--surface2);border:1px solid var(--border);color:var(--text);padding:6px 12px;border-radius:6px;font-size:12px;cursor:pointer;transition:all .2s;display:flex;align-items:center;gap:6px}',
        '.action-btn:hover{background:var(--border);border-color:var(--accent)}',
        '.action-btn.secondary{color:var(--text2)}',
        '.action-btn.secondary:hover{color:var(--orange);border-color:var(--orange)}',
        '#filter-bar{display:flex;align-items:center;gap:10px;padding:8px 20px}',
        "#filter-input{flex:1;background:var(--surface2);border:1px solid var(--border);border-radius:8px;padding:6px 12px;color:var(--text);font-size:12px;font-family:'Segoe UI',system-ui,sans-serif;outline:none;transition:border-color .2s}",
        '#filter-input:focus{border-color:var(--accent)}',
        '#filter-input::placeholder{color:var(--text2)}',
        '#filter-chips{display:flex;gap:4px;flex-shrink:0}',
        '.chip{background:var(--surface2);border:1px solid var(--border);border-radius:16px;padding:3px 12px;color:var(--text2);font-size:11px;cursor:pointer;transition:all .2s;white-space:nowrap}',
        '.chip:hover{color:var(--text);border-color:var(--accent)}',
        '.chip.active{background:var(--accent);color:#fff;border-color:var(--accent)}',
        '.debug-badge{font-size:11px;font-weight:700;color:var(--red);padding:4px 10px;border-radius:12px;background:#f8514922;animation:pulse 2s infinite}',
        '@keyframes pulse{0%,100%{opacity:1}50%{opacity:.6}}',
        '#content{flex:1;overflow:hidden}',
        '.tab-panel{display:none;height:100%;overflow:auto}',
        '.tab-panel.active{display:flex}',
        '#split{display:flex;width:100%;height:100%;gap:1px;background:var(--border)}',
        '.panel{flex:1;background:var(--bg);padding:16px;overflow:auto}',
        '.panel-header{display:flex;align-items:center;gap:8px;margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--border)}',
        '.panel-header h2{font-size:13px;text-transform:uppercase;letter-spacing:1px;color:var(--text2);margin:0;padding:0;border:none}',
        '.count-badge{font-size:11px;color:var(--accent);background:var(--surface2);padding:2px 8px;border-radius:10px}',
        '.thread{margin-bottom:12px;border:1px solid var(--border);border-radius:8px;overflow:hidden;transition:border-color .2s}',
        '.thread:hover{border-color:var(--accent)}',
        '.thread.filtered-out{display:none}',
        '.thread-header{display:flex;align-items:center;gap:8px;padding:10px 14px;background:var(--surface);cursor:pointer;user-select:none}',
        '.thread-header .dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}',
        '.dot.running{background:var(--green);box-shadow:0 0 6px var(--green)}',
        '.dot.waiting{background:var(--orange);box-shadow:0 0 6px var(--orange)}',
        '.dot.stopped{background:var(--red);box-shadow:0 0 6px var(--red)}',
        '.thread-header .name{font-size:13px;font-weight:600;flex:1}',
        '.thread-header .tid{font-size:11px;color:var(--text2)}',
        '.thread-header .frame-count{font-size:10px;color:var(--accent);background:var(--surface2);padding:1px 6px;border-radius:8px}',
        '.frame-list{display:none}',
        '.thread.open .frame-list{display:block}',
        '.frame{padding:8px 14px 8px 28px;border-top:1px solid var(--border);font-size:12px;cursor:pointer;transition:background .15s}',
        '.frame:hover{background:var(--surface2)}',
        '.frame.filtered-out{display:none}',
        ".frame .method{color:var(--cyan);font-family:'Cascadia Code','Fira Code',monospace}",
        '.frame .module{color:var(--text2);margin-left:6px;font-size:11px}',
        '.locals{padding:4px 0 4px 16px;margin-top:4px}',
        ".local{display:flex;align-items:center;gap:6px;padding:3px 0;font-size:11px;font-family:'Cascadia Code','Fira Code',monospace}",
        '.local .lname{color:var(--accent2)}',
        '.local .ltype{color:var(--text2)}',
        '.local .lval{color:var(--green)}',
        '.local .arrow{color:var(--red);cursor:pointer;text-decoration:underline;font-size:10px}',
        '.local .arrow:hover{color:var(--orange)}',
        '.highlight{background:var(--orange);color:#000;border-radius:2px;padding:0 1px}',
        '.heap-obj{border:1px solid var(--border);border-radius:8px;margin-bottom:10px;overflow:hidden;animation:fadeIn .3s ease}',
        '.heap-obj .obj-header{padding:10px 14px;background:var(--surface);display:flex;justify-content:space-between;align-items:center}',
        ".heap-obj .obj-type{color:var(--cyan);font-size:13px;font-weight:600;font-family:'Cascadia Code','Fira Code',monospace}",
        '.heap-obj .obj-addr{font-size:11px;color:var(--accent2);font-family:monospace}',
        '.heap-obj .obj-meta{display:flex;gap:12px;padding:8px 14px;font-size:11px;color:var(--text2)}',
        '.gen-badge{padding:2px 8px;border-radius:4px;font-size:10px;font-weight:700}',
        '.gen0{background:#3fb95022;color:var(--green)}',
        '.gen1{background:#d2992222;color:var(--orange)}',
        '.gen2{background:#f8514922;color:var(--red)}',
        '.obj-fields{padding:6px 14px 10px}',
        '.obj-field{display:flex;gap:8px;padding:2px 0;font-size:11px;font-family:monospace}',
        '.obj-field .fname{color:var(--accent)}',
        '.obj-field .fval{color:var(--green)}',
        '.refs-section{padding:6px 14px 10px;border-top:1px solid var(--border)}',
        '.refs-section h4{font-size:11px;color:var(--text2);margin-bottom:4px}',
        '.ref-link{color:var(--accent2);font-size:11px;cursor:pointer;font-family:monospace;margin-right:8px}',
        '.ref-link:hover{color:var(--accent);text-decoration:underline}',
        '#tab-stats{flex-direction:column;padding:20px}',
        '#stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:20px}',
        '.stat-card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px;text-align:center;transition:transform .2s,border-color .2s}',
        '.stat-card:hover{transform:translateY(-2px);border-color:var(--accent)}',
        '.stat-card .stat-val{font-size:28px;font-weight:700;background:var(--gradient);-webkit-background-clip:text;-webkit-text-fill-color:transparent}',
        '.stat-card .stat-label{font-size:11px;color:var(--text2);margin-top:4px;text-transform:uppercase;letter-spacing:1px}',
        '.type-table{width:100%;border-collapse:collapse;margin-top:16px}',
        '.type-table th{text-align:left;padding:8px 12px;font-size:11px;text-transform:uppercase;color:var(--text2);border-bottom:2px solid var(--border)}',
        '.type-table td{padding:8px 12px;font-size:12px;border-bottom:1px solid var(--border);font-family:monospace}',
        '.type-table tr:hover td{background:var(--surface2)}',
        '.bar{height:6px;border-radius:3px;background:var(--surface2);overflow:hidden;min-width:60px}',
        '.bar-fill{height:100%;border-radius:3px;background:var(--gradient);transition:width .5s ease}',
        '#heapCanvas{width:100%;height:100%;background:var(--bg)}',
        '@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}',
    ].join('\n');
}
