name: Build and Deploy Extension

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Extension
        run: npm run compile

      - name: Package Extension
        run: npx @vscode/vsce package --allow-missing-repository

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

  release:
    name: Release and Publish
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download VSIX Artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        # Note: You must add VSCE_PAT to your GitHub Repository Secrets
